CC       := /home/zheng/.clang/bin/clang
CXX      := /home/zheng/.clang/bin/clang++
AS       := /home/zheng/.clang/bin/clang
AR       := /home/zheng/.clang/bin/llvm-ar
STRIP    := /home/zheng/.clang/bin/llvm-strip

CXXFLAGS := --gcc-install-dir=/usr/lib/gcc/x86_64-linux-gnu/11

include Makefile

PREFIX   = ~/lfi-bench/benchmark-lib/aarch64-lfi-clang
