CC       := /users/paleshel/.local/bin/clang
CXX      := /users/paleshel/.local/bin/clang++
AS       := /users/paleshel/.local/bin/clang
AR       := /users/paleshel/.local/bin/llvm-ar
STRIP    := /users/paleshel/.local/bin/llvm-strip

CXXFLAGS := --gcc-install-dir=/usr/lib/gcc/x86_64-linux-gnu/11

include Makefile

PREFIX   = ~/lfi-bench/benchmark-lib/aarch64-lfi-clang
